### ISSUE TITLE
f5-sdk is a dependency of f5-openstack-agent so it doesn't require a separate install.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2#24]
I'm not sure which of @richbrowne, @jlongstaf, and @jputrino this should be assigned to.  Ping me back and let me know and I'll quit @ mentioning the others.

See 'setup.py' in 'f5-openstack-agent', since the 'install_requires' list contains the element 'f5-sdk >= 0.1.2', it is not necessary to explicitly mention the `f5-sdk` in this readme.    The "Install the F5® SDK" section should be removed entirely.

**Comment by jputrino** [comment]
@richbrowne and I were under the impression initially that we did have to install the SDK separately. Can we have a quick discussion when I'm in the office tomorrow afternoon?
