### ISSUE TITLE
Additions to prerequisites in deployment guide

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv2#46]
#### OpenStack Release
Liberty

#### Description
Per email from Haitao, the deployment guide instructions need to state a few additional prerequisites (functional OpenStack deployment with Neutron installed). Discuss with @mattgreene to see if any other additions are needed.

**Comment by mattgreene** [comment]
Here are the enhancements:
1. Explicitly state the supported OpenStack release, such as Liberty at the top of the of documentation
2. Move the Compatibility section to the top
3. Add a "Note" for dependency on neutron and lbaas packages being installed, we presume that the user is installing the F5 lbaas code onto the neutron server.
4. "pip install" commands should change to reflect the official packages on pypyi, not our git repos.
